# permissions for end users to view inappmetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inappmetric-viewer-role
rules:
- apiGroups:
  - argo-in-app.io
  resources:
  - inappmetrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argo-in-app.io
  resources:
  - inappmetrics/status
  verbs:
  - get
