apiVersion: argo-in-app.io/v1
kind: InAppMetric
metadata:
  name: inappmetric-sample
spec:
  schedule: "*/1 * * * *"
  metrics: 
  - name: test
    provider:
      prometheus: 
        address: http://127.0.0.1:9090
        query: "container_cpu_user_seconds_total"
  - name: test2
    provider:
      prometheus: 
        address: http://127.0.0.1:9090
        query: "machine_cpu_cores"
  - name: test3
    successCondition: result[0] == 4
    provider:
      prometheus: 
        address: http://127.0.0.1:9090
        query: "machine_cpu_sockets"

