apiVersion: argo-in-app.io/v1
kind: InAppMetric
metadata:
  name: inappmetric-main
  annotations: 
    notifications.argoproj.io/subscribe.on-analysis-run-error.whname: ""
spec:
  schedule: "*/2 * * * *"
  runLimit: 4
  metrics: 
  - name: test
    provider:
      prometheus: 
        address: http://127.0.0.1:9090
        query: "container_cpu_user_seconds_total"
  - name: test2
    successCondition: result[0] == 4
    provider:
      prometheus: 
        address: http://127.0.0.1:9090
        query: "machine_cpu_cores"
  - name: test3
    interval: 1m
    count: 2
    failureLimit: 1
    successCondition: result[0] == 4
    provider:
      prometheus: 
        address: http://127.0.0.1:9090
        query: "machine_cpu_sockets"

